---

- name: Deploy Image
  docker_container:
    name: flask
    image: yossibnv/python-app:{{ version }}
    state: started
    restart: yes
    ports:
     - "80:80"
     

- name: Check that a page returns a status 200 and fail if 'Hello World' is not in the page contents
  uri:
    url: http://{{ myHost }}  
